### ISSUE TITLE
[SDL 0248] HMI Policy Table Update using vehicle modem

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_hmi#228] opened 2019-09-03 17:15 UTC
Add configurations and support for the proposal described and linked below:

Proposal: [HMI Policy Table Update using vehicle modem](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0248-hmi-ptu-support.md)

> This proposal describes an enhanced policy table update PTU sequence where the IVI system sends the policy table snapshots (PTS) directly to the policy server using the in-vehicle modem and returns a policy table update (PTU) back to SDL Core without using any `SystemRequest` RPC.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/813

Steering Committee Decision:

>The Steering Committee voted to accept this proposal with the following revisions:
- Note `SDL.GetURLs` as deprecated, and add `GetPolicyConfigurationData`
- Include implementation details for HMI Integration Guidelines, SDL HMI, Generic HMI, and ATF/ATF Test Scripts, as outlined in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/813#issuecomment-525335714)

> The proposal .md file was updated to reflect these revisions on 9/3/19.

**Comment by AStasiuk** [comment] 2019-11-28 08:18
@theresalech, could you please create a core issue for this proposal as well, because we expect core changes also.
Could you please include this proposal in the Q1 release 2020?
Core/HMI/SDL HMI Integration Guidelines/ATF parts will be ready for Livio review in the middle of December.

**Comment by theresalech** [comment] 2019-12-02 19:07
@AStasiuk a Core issue was not entered for this feature as the proposal stated `Existing code of Core should not be affected.` If Core changes are needed, a proposal to revise SDL 0248 should be entered.  Thanks!

**Comment by LitvinenkoIra** [comment] 2019-12-03 10:03
In order to implement the logic that are indicated in the proposal, the following changes are necessary from the SDL Core side: 
1. For  EXTERNAL_PROPRIETARY policy flow: 
SDL should change the internal status to UPDATING and send SDL.OnStatusUpsate to HMI right after receiving a successful SDL.PolicyUpdate response (For now SDL changes the status after sending the OnSystemRequest to the mobile, but in the new in-vehicle modem PTU sequence there are no any mobile requests)
2. For all policy flows: SDL should restart the internal PTU timeout in case SDL received BC.OnSystemRequest with type PROPRIETARY or HTTP from HMI in UPDATING state (Because if the policy backend cannot be reached or isn't reached by the modem and the HMI sends OnSystemRequest to SDL for getting PTU via mobile - SDL should give the mobile app time to perform PTU for backward compatibility with existing behavior)

**Comment by AStasiuk** [comment] 2019-12-03 11:24
@theresalech, please note, that in the original proposal was noted **Impacted Platforms: [Core / HMI]**.
Also, the possibility of **Potentially modify Core (if needed) to make this feature work** was explicitly given in the section [Impact on existing code](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0248-hmi-ptu-support.md#impact-on-existing-code), point  4.
Also, according to [comment](https://github.com/smartdevicelink/sdl_evolution/issues/813#issuecomment-525335714) from @JackLivio it was admitted the possibility of the changes in the Core.
Please let me know is the revision of the proposal is still required?
@kshala-ford, I would let to know your opinion as a proposal author.

**Comment by theresalech** [comment] 2019-12-03 14:29
@AStasiuk - while it was understood that there was a possibility Core changes would be required for this feature, the changes themselves were unknown.  Now that it's confirmed Core changes are needed, we should describe them in the proposal via revisions.  This will help to ensure the Steering Committee is aware of the changes required and agrees with the proposed approach.  Thanks!

**Comment by kshala-ford** [comment] 2019-12-05 14:20
@theresalech the fact that the proposal is saying that Core is an impacted platform the PM should create an issue in sdl_core regardless of what's written in the proposal. This issue could be closed with no change If we would have confirmed that existing code of Core isn't affected.

The proposal states `only very minor changes to SDL Core are expected` and `Potentially modify Core (if needed) to make this feature work`. In the sdl_hmi repo we identified that a Core change is needed.

The necessary changes to SDL Core described in https://github.com/smartdevicelink/sdl_hmi/issues/228#issuecomment-561093424 by @LitvinenkoIra are already contained in the proposal. See below rationale:

|1. 

> For EXTERNAL_PROPRIETARY policy flow:
SDL should change the internal status to UPDATING and send SDL.OnStatusUpdate to HMI right after receiving a successful SDL.PolicyUpdate response...

is described in the diagram of the proposal (see https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0248-hmi-ptu-support.md#proposed-solution) and in textual form:

> SDL should transit to the UPDATING status if the HMI responds successfully to the BasicCommunication.PolicyUpdate request from SDL.

This alone justifies opening an sdl_core issue.

|2. 

> For all policy flows: SDL should restart the internal PTU timeout in case SDL received BC.OnSystemRequest with type PROPRIETARY or HTTP from HMI in UPDATING state  ...

Is already described for the SDL HMI side and is part of the existing requirement described in the diagram (previously OnSystemRequest changes state to UPDATING, now OnSystemRequest is within state UPDATING).

The second bullet point in @LitvinenkoIra is just the textual form of what's described in the diagram. It's not about adding new logic to sdl_core. The PTU timer already exist and the change to SDL Core is make sure the PTU timer still works properly when a modem update fails. From my point of view this is what I have expected as a very minor change to SDL Core or at least as an implementation detail.

|Conclusion

The proposal already contains what's needed. Revising the proposal takes weeks and doesn't add lot of value. Let's agree on the implementation details in an sdl_core issue.

**Comment by theresalech** [comment] 2019-12-05 18:02
@kshala-ford understood, thanks for the additional information.  I've created a Core issue for the implementation of this feature: https://github.com/smartdevicelink/sdl_core/issues/3161.

**Comment by ShobhitAd** [comment] 2020-02-05 20:10
Closing with the merge of https://github.com/smartdevicelink/sdl_hmi/pull/271

**Closed by ShobhitAd** 2020-02-05 20:10 UTC
Labels: proposal
