### ISSUE TITLE
HMI Uncaught ReferenceError during processing SetDisplayLayout(displayLayout = DEFAULT)

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#534] opened 2021-03-23 10:37 UTC
**Description:**
HMI Uncaught ReferenceError during processing SetDisplayLayout(displayLayout = DEFAULT)

**Precondition:**
1. SDL and HMI are started
2.  Media mobile app is registered and activated

**Steps to reproduce:**
1. App requests SetDisplayLayout(displayLayout = DEFAULT)

**Expected result:**
HMI responds with
{"success":true,"resultCode":"SUCCESS"}
HMI applies appropriate template

**Actual result:**
SDL -> HMI [10:48:44:366]: {"id":601,"jsonrpc":"2.0","method":"UI.SetDisplayLayout","params":{"appID":1246083497,"displayLayout":"DEFAULT"}}
UIRPC.js:157 FFW.UI.onRPCRequest
UIRPC.js:514 FFW.UI.SetDisplayLayoutResponse
UIRPC.js:517 Uncaught ReferenceError: Cannot access 'model' before initialization
    at d.onRPCRequest (UIRPC.js:517)
    at d [as onRPCRequest] (ember-1.0.pre.min.js:14)
    at d.onWSMessage (RPCClient.js:190)
    at WebSocket.socket.onmessage (RPCClient.js:81)

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/7.1.0-RC1
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (7fad546)
SPT: SPT: 20210305-Android (1076)

**Comment by Ypostolov** [comment] 2021-04-20 16:48
@jordynmackool This issue is reproduced on HMI because SetDisplayLayout is deprecated RPC in HMI_API.xml, to fix the issue we can delete all the relevant code on HMI, please advise whether this solution is acceptable?

**Comment by JackLivio** [comment] 2021-04-21 14:25
@Ypostolov Deprecated does not yet mean removed, we should look at fixing the javascript error. Maybe in future we can create a core change for transforming set display layouts into show requests.

**Comment by JackLivio** [comment] 2021-05-07 14:45
Entered a proposal for this issue: https://github.com/smartdevicelink/sdl_evolution/pull/1136

**Comment by Ypostolov** [comment] 2021-05-19 12:55
@jordynmackool PR with fix is ready for Livio review. Thank you.

**Comment by JackLivio** [comment] 2021-06-03 14:30
Fixed by #566

**Closed** 2021-06-03 14:30 UTC
Labels: bug
