### ISSUE TITLE
Web app with HMI type WEB_VIEW is not registered and activated 

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#422] opened 2020-10-19 10:04 UTC
**Bug Report**
POP-UP "runWebEngineAppView" menu is not observed during activation the WebEngine (WEB_VIEW) App on HMI
Web app with HMI type WEB_VIEW is not registered and activated 

**Preconditions:**
1. Update preloaded_pt.json: Add to "app_policies"

   {"hello-webengine4": {
   "AppHMIType": [ "WEB_VIEW" ],
    "keep_context": false,
    "steal_focus": false,
    "priority": "NONE",
    "default_hmi": "NONE",
    "groups": ["Base-4", "WidgetSupport"],
     "hybrid_app_preference": "CLOUD",
     "enabled": false,
     "transport_type ": "WS"}

2. Web app (hello-webengine4 data) in HMI folder sdl_hmi/web_engine/hello-webengine4
3. In HMI folder, run `./deploy_server.sh` as a back-end process
4. SDL and HMI are started

**Reproduction Steps**
1. On HMI → Apps →Apps Store → Set Apps Properties
Add properties for hello-webengine4 app:

{
  "nicknames": [
    "Hello WebEngine4"
  ],
  "policyAppID": "hello-webengine4",
  "enabled": true,
  "transportType": "ws",
  "hybridAppPreference": "BOTH"
}

2. Activate a Web app (WEB_VIEW) on the HMI
On HMI → Apps → Hello WebEngine4

3. Click "Activate App" button on "runWebEngineAppView" menu on HMI

**Expected Behavior**
1. HMI → SDL: SetAppProperties ( properties: { nicknames:
{ "Hello WebEngine4" }, policyAppID:"hello-webengine4", enabled: true, transportType:"ws", hybridAppPreference: "BOTH" }
SDL → HMI: SetAppProperties ({ success:true, resultCode: "SUCCESS" }))
SDL → HMI: UpdateAppList: (...
{"applications":["appName":"Hello WebEngine4"... ] )
HMI → SDL: UpdateAppList response ( SUCCESS )

The Web app is visible in the main window on the HMI

2. POP-UP "runWebEngineAppView" menu is observed

HTML path: http://localhost:8082/web_engine/hello-webengine4/./index.html
SDL host: localhost
SDL port: 2020
SDL transport: ws-server

3. Web app is registered and activated successfully

**Observed Behavior**
1. HMI → SDL: SetAppProperties (properties:{ nicknames:
{ "Hello WebEngine4" }, policyAppID:"hello-webengine4", enabled: true, transportType:"ws", hybridAppPreference: "BOTH" }
SDL → HMI: SetAppProperties ({ success:true, resultCode: "SUCCESS" }))
SDL → HMI: UpdateAppList: ({"applications":["appName":"Hello WebEngine4"... ] )
HMI → SDL: UpdateAppList response ( SUCCESS )

The Web app is visible in the main window on the HMI

Info Message is observed on HMI logs:
RPCSimpleClient.js:48 WebSocket connection to 'ws://127.0.0.1:8081/' failed: WebSocket is closed before the connection is established.

2. POP-UP "runWebEngineAppView" menu is not observed

**OS & Version Information**
OS/Version: Ubuntu 16.04
SDL: https://github.com/smartdevicelink/sdl_core/tree/7.0.0-RC1 (5c72cdd)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (2cfbe48)
sdl_javascript_suite: https://github.com/smartdevicelink/sdl_javascript_suite (2e8f3d7)

**Logs:**
[SDL_logs.zip](https://github.com/smartdevicelink/sdl_hmi/files/5400962/SDL_logs.zip)

**Comment by AKalinich-Luxoft** [comment] 2020-10-19 18:48
@theresalech Please notice the issue is a regression caused by [this commit](https://github.com/LuxoftSDL/sdl_hmi/commit/727d0d3183958d343ea637a6c54c4aa717a552cc) which is in the scope of 7.0 Release.
Fix is ready for Livio review

**Comment by iCollin** [comment] 2020-10-19 18:52
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/425

**Closed by iCollin** 2020-10-19 18:52 UTC
