### ISSUE TITLE
HMI sets forwardSeekIndicator and backSeekIndicator parameters for multiple Apps during SetMediaClockTimer request

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_hmi#519] opened 2021-03-17 16:49 UTC
**Description:**
HMI sets forwardSeekIndicator and backSeekIndicator parameters for multiple Apps during SetMediaClockTimer request from App1

**Precondition:**
    1. SDL and HMI are started
    2. App1 and App2 with HMI type 'Media' are registered
    3. App1 is activated
    4. App1 sends SetMediaClockTimer RPC with:
      "updateMode":"COUNTUP",
      "startTime": { "hours":0, "minutes":15, "seconds":30 },
      "backSeekIndicator": {"seekTime":30,"type":"TIME" },
      "forwardSeekIndicator": { "seekTime":30,"type":"TIME"}
    5. The seek indicators are "TIME" for App1
    'SEEKLEFT' button with "ico_seek_left.png" image is observed on HMI
    'SEEKRIGHT' button with "ico_seek_right.png" image is observed on HMI

**Steps to reproduce:** 
1. Activate App2

**Expected result:**
1. App2 is activated successfully
2. By default the seek indicators are "TRACK":
    SEEKLEFT' button with "ico_prew.png" image is observed on HMI for App2
    'SEEKRIGHT' button with "Ico_next.png" image is observed on HMI for App2

**Actual result:**
1. App2 is activated successfully
2. The seek indicators are "TIME"
    'SEEKLEFT' button with "ico_seek_left.png" image is observed on HMI
    'SEEKRIGHT' button with "ico_seek_right.png" image is observed on HMI
![App2](https://user-images.githubusercontent.com/45170482/111506057-e9d3ba80-8751-11eb-8446-410e1bbf0d19.png)

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (fed2ae4)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (ad2dc80)
SPT: 20210305-Android (1076)

**Comment by VjKlepikov** [comment] 2021-03-17 16:59
@jordynmackool, Please notice this issue is related to feature Media Skip Indicators that should be released in the 7.1 release.

**Comment by Ypostolov** [comment] 2021-03-22 15:06
Luxoft is working on it.

**Comment by jordynmackool** [comment] 2021-03-22 15:54
@Ypostolov please note @jacobkeeler may have already started working on a fix for this reported bug. Please allow me a day to confirm before you continue working on a fix so efforts are not duplicated.

**Comment by jacobkeeler** [comment] 2021-03-23 13:40
@Ypostolov I was able to investigate the issue for a while on Thursday, but I wasn't able to find the actual root cause as of yet. I should be able to take on another task if Luxoft is planning on looking into the fix. Some notes I have from my investigation:

1. The reproduction steps are rather specific. If you set streaming indicators for both apps, the HMI sets them correctly from that point on.
2. Looking in the debugging console, it looks like the model for app2 actually has `forwardSeekIndicator` and `backSeekIndicator` set to `{"seekTime":30,"type":"TIME"}` in the scenario given, same as app1. This leads me to believe that parts of the model for app1 and app2 are tied together initially (possibly because of some nuance in how javascript and/or ember-js stores data).

**Comment by jordynmackool** [comment] 2021-03-23 14:31
Thanks, @jacobkeeler. @Ypostolov, please let me know when a PR is ready for Livio review.

**Comment by jordynmackool** [comment] 2021-03-30 15:07
@Ypostolov please advise when the fix for this issue will be ready for Livio review?

**Comment by LitvinenkoIra** [comment] 2021-03-31 08:05
@jordynmackool fix for this issue is currently in progress and will be ready for Livio review by the end of this week

**Comment by LitvinenkoIra** [comment] 2021-04-01 13:29
@jacobkeeler Fix is ready for Livio review. Thank you.

**Comment by jacobkeeler** [comment] 2021-04-01 15:19
Closing with the merge of #550

**Closed by jacobkeeler** 2021-04-01 15:19 UTC
Labels: 5.5.0 Release, bug
