### ISSUE TITLE
AlertManeuver pop-up displays the softButtons from previous requests

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_hmi#352] opened 2020-04-28 18:43 UTC
Bug Report: AlertManeuver pop-up displays the softButtons from previous requests

**Reproduction Steps**
1. Start SDL and HMI
2. Mobile app is registered and activated
3. App requests AlertManeuver with softButtons
4. First AlertManeuver request is successfully processed
5. App requests seconds AlertManeuver with softButtons
6. Second AlertManeuver request is successfully processed
7. App requests Alert with softButtons
8. App requests third AlertManeuver with softButtons

**Expected Behavior**
AlertManeuver pop-up is shown with the softButtons number defined in the request

**Observed Behavior**
AlertManeuver pop-up displays the softButtons from previous requests

**OS & Version Information**
SDL: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC2 ceb4d9c
sdl_hmi branch: develop
commit: https://github.com/smartdevicelink/sdl_hmi/commit/7a7e6acddc12b8b4e9d2b98df9c09ee423f6356d

**Comment by Ypostolov** [comment] 2020-08-07 08:30
@theresalech PR with fix is ready for Livio review.

**Comment by iCollin** [comment] 2020-10-09 19:02
@Ypostolov is this issue still actual on develop? I am unable to reproduce.

**Comment by iCollin** [comment] 2020-10-09 19:40
@Ypostolov is this issue still actual on develop? I could not reproduce with the steps from the issue description.

**Comment by AKalinich-Luxoft** [comment] 2020-10-12 20:11
@iCollin yes, it is still actual for develop. I suggest to use the following steps:
1. SDL and HMI are started
2. Application with allowed `AlertManeuver` and `Alert` rpc is registered and activated
3. Send `AlertManeuver` with three soft buttons. Wait for popup is closed
4. Send `Alert` with two soft buttons. Wait for popup is closed
5. Send `AlertManeuver` with three soft buttons. Observe the issue:

![Screenshot from 2020-10-12 16-06-26](https://user-images.githubusercontent.com/5848997/95786419-7d85f400-0ca5-11eb-84da-d6c9d93f0a9f.png)

Linked PR solves that issue.

**Comment by iCollin** [comment] 2020-10-13 16:18
Closed via https://github.com/smartdevicelink/sdl_hmi/pull/393

**Closed by iCollin** 2020-10-13 16:18 UTC
